---
production:
  secret_key_base: 963365e80c3b379754ab1277d54fbb5e68a4833131f03e4a097165568e900190d5e0f57d565f0b611be69f70c8cfbd06f47fbf7e9966793b6bc802c8d323efb6
  otp_key_base: e62021080e20756e9a650079ac9794a88f0d312331512d639e468d8aaf8bd44b45322884197f3cd5bd5c699fe4949aee29bb8fa9d749260cac37f7294c04d1de
  db_key_base: 76fd4c76ad88731035c849ba42fbe298742776b52a2c27c25181a08a8d4b1755ae19870fec0bca8b21060a2f1b960ff958ba861e25580a1474e1f3bb63152883
  openid_connect_signing_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEA8j0zUt2skIwEipO0lQC+SdeOxYTE/Lnkszx2b49wpD7pyrAf
    Si7WI5Z4dTanFaBoA2z79TWZ2kKP7aS5AKOeOmVCAR+kdE+e40bjRncagnhRZMP7
    A4GYQu43h/WY6xQNGQ3b/W1wfZ6TKoHqrDtw53ykPf9CX/bKehDXgMlG/rjkmiJY
    RZ09wU7of9971uhKvp3rMFiIfMjU2jAiQi0rz0NTvQNNFi+bmXTBB+th/l6x7dR+
    iwndjOyMPtag+pW1q/zStVPSXGC3KrDerZIWgLBo/kIf64CvDAG6bzNT5C+UAvtD
    uBX3lu6g7YOry8H2YskE/rdxbu9O82umadDSNQIDAQABAoIBAQDmVlVwLUMCa3GC
    B7NFn+BRPLwQiw/4tBaIbCy+JenY883BIrmOA30xd8nwwtgb01w0LbRjVOWHyZUs
    Rl54AhzZsCEUCm+I/ZC60lQYU/aMKzZSF5yel+MdeYCqMlmG5pkRwsD1eNPnTxrm
    54Qq45aXN0jBfvAxaezcJxmT51AvsexsCu/mjBH7rabQMLRWK1eHhejzObk6U7HM
    mp0IkgzdPpTnlQydzwZd2+CVHJAxgIgDJnztnnZK2CGI07j2EjxUB+VjvJPiMkcU
    WYSsFqPrWBz1baVzUtGxxcbMxjdJqkX53i8d1Ja87bnzTSEFgZ6gYVQoHrfsw0C4
    Y0/IFSXdAoGBAPr66rmcApMGGFsY51UcgzOZ+cb81i5gSO32gy6yxDrgSsTjo3hY
    2j95UW7FawlYTxHGMVgIOTHJaZf37nPLVXUXqXxXcYi0+jFNZ8tfH0Q7LdAI38PR
    EyUb3uIOi9ZpiptehJ4527C/+zmDkqknH7zPkDd0G70xbWP0wGch5BLDAoGBAPcV
    hunFjzYoqBV7NzcvdWV6zAt7jp/6/7wqJanHfP+1dwTY8oHhmLKsiG8846HInFX2
    BtXlBSF+k7vj7mBa4rotCmKhdg0KdwUFj+0ucyZlUpTkulArZrHcjRv+UgB32UFv
    pVi57krTkFoHnpwz4+yOyh0thmEM+5RPBInhkcenAn9Glktt6HLQ5uXyuQ5W4a4E
    1UlqrbGPWYUpaCt89so5xNtChMN1FYhMUdKVVPDFsBCM7zDxkV6EoiEQnKpz5rwi
    MoV4cx97U2sKcrq+eAJTLlG0MMq+SA8aYLxO18h8hTJ2gB7MYXloPJZrlpWo/Vfv
    wnDNJ9qlW0Fo221BlEaRAoGBALKeRE6g+/up/oCw92SUkWiQEgvHAX8Tg2ZyjZGj
    3fA5LdY6Q22zOaEI6wSHXwOos6PM3HoqOsBQ8dmlV8EeUsNGJjjRAjdBNnNR5w8O
    Qj4ih0WN6EZmabHwf64Z9wvRmCQe4sg2eVZshPEgiv/e30k2nFPlgjyMlx5K1Twb
    7jgHAoGAG9RR57lewMcL3Fki9IfYNfi+d3oeHK3fvrv+bku/jcyIGN0Ao61f3HBS
    8qldV1eBBGOiezNLTeixok054kLnAe9l6pw4ArLouShaAo0+XgTYtUMkGO+sgCR/
    4OzsVuwTfkQ8oB9p0nGqFvkOGQF9Kejg6a/aNWGrFiSy92gtQ0s=
    -----END RSA PRIVATE KEY-----
